apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/argocd-project-registry.git
    targetRevision: HEAD
    path: pr-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    # Sync policy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
