#!/bin/bash -ex

# commiting this as an example of a script we can use to auto-generate the kustomization.yaml
# files in `stable` and `test` repos

# refresh.sh
# Create a kustomization.yaml and then add all kubernetes YAMLs into resources...
: "${1:?Specify the directory to put the kustomization file into}"
STARTING_DIR="$PWD"
cd "$1"
echo -n "# built by ./scripts/refresh-kustomize.sh $1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
" > kustomization.yaml
yamls="$(find . -type f -name "*.yaml" | grep -v kustomization.yaml | sort)"
for y in "${yamls[@]}"; do
  kustomize edit add resource $y
done
cd "$STARTING_DIR"
