apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stable-apps
  namespace: argocd
  labels:
    release: stable
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/cluster-A-qa-argocd-registry.git
    targetRevision: HEAD
    path: stable
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    # Sync policy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
