apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-registry
  namespace: argocd
  labels:
    release: stable
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/cluster-A-qa-argocd-registry.git
    targetRevision: kustomize_test
    path: stable
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    # Sync policy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
