apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-apps
  namespace: argocd
  labels:
    release: pr
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/argocd-project-registry.git
    targetRevision: kustomize_test
    path: test
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    validate: true
