apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/cluster-A-qa-argocd-registry.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    validate: true
