apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    release: stable
    buildNumber: '11'
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
