apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Chart.Name }}
  namespace: argocd
spec:
  description: Example Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
