apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sock-shop-front-end-{{ .Values.release }}"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/citizenken/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-socks-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: "sock-shop-front-end-{{ .Values.release }}"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "sock-shop-front-end-{{ .Values.release }}"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: Example Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

