apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop-front-end
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sock-shop-front-end-workflow
  namespace: sock-shop-front-end
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
  - list
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-default-workflow
  namespace: sock-shop-front-end
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-front-end-workflow
subjects:
- kind: ServiceAccount
  name: default
  namespace: sock-shop-front-end
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: sock-shop-front-end
  namespace: argocd
spec:
  description: Example Project
  destinations:
  - namespace: sock-shop-front-end*
    server: https://kubernetes.default.svc
  - namespace: argo
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    release: stable
  name: sock-shop-front-end
spec:
  destination:
    namespace: sock-shop-front-end
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles: qa-values.yaml
    path: helm-chart
    repoURL: https://github.com/citizenken/front-end.git
    targetRevision: v1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
